[package]
name = "xplorer"
version = "0.1.0"
edition = "2021"

[dependencies]
btleplug = "0.11.6"
tokio = { version = "1.40.0", features = ["full"] }
futures = "0.3.31"
thiserror = "1.0.64"
uuid = "1.10.0"
